### ISSUE TITLE
Entity is not reconized in macro for picture-entity

### ISSUE THREAD

**Issue by jmgiaever** [thomasloven/hass-lovelace_gen#20]
This is my yaml (which is included!)
```
# lovelace_gen
{% macro user_photo(entity, ws) -%}
{{"  "*ws}}- type: picture-entity
{{"  "*ws}}  entity: {{ entity }}
{{"  "*ws}}  image: "/local/img.jpg"
{%- endmacro %}
title: Example
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          {{ user_photo('person.joachim_m_giaever', 3) }}
      - type: glance
        entities: 
          - entity: lock.entrance_door_lock
            name: "Entrance door"
            tap_action: 
              action: toggle
          - entity: binary_sensor.office_door_state
            name: "Office"
          - entity: binary_sensor.bedroom_window_state
            name: "Bedroom window"
```

The frontend is giving me the error:

```
Invalid Configuration: 'entity' required
type: picture-entity
```
I've tested that «the person» exists and tried to look for indentation errors. I'm wondering why I need to set 3xIndent in my method, but when I'm counting, I'll count 5. 

I'm using HA 0.115.6. and latest version available of `lovelace_gen` in HACS.
