### ISSUE TITLE
setup with mixed storage and yaml modes

### ISSUE THREAD

**Issue by dkebler** [thomasloven/hass-lovelace_gen#22]
I've gone from strictly yaml mode to storage mode additional dashboards (that in in yaml mode).
What/where would be the way to set lovelace_gen in this case?

in configuration.yaml
```
lovelace:
  mode: storage
  dashboards: !include lovelace/dashboards.yaml
```

in lovelace/dashboards.yaml
```
lovelace-panel:
  mode: yaml
  title: Manual - Panel
  icon: mdi:script
  show_in_sidebar: false
  filename: lovelace/panel.yaml
lovelace-manual:
  mode: yaml
  title: Manual
  icon: mdi:script
  show_in_sidebar: false
  filename: lovelace/manual.yaml
```
