### ISSUE TITLE
Working with Multiple Dashboards

### ISSUE THREAD

**Issue by nathanmfast** [thomasloven/hass-lovelace_gen#35]
Is there any way to process separate dashboard yaml files with `lovelace_gen`?

I understand that this plugin looks at `ui-lovelace.yaml` and finds all the files that are included via `!include` statements, and if any of those files begin with `# lovelace_gen` it will perform its pre-processing on them. 

In my `configuration.yaml` I have a bunch of dashboards defined under `lovelace:` so the relevant portion looks like this:
```
lovelace_gen:

lovelace:
  mode: yaml
  dashboards:
    upstairs-mobile-dashboard:
      mode: yaml
      title: Upstairs
      icon: mdi:home-floor-3
      show_in_sidebar: true
      filename: dashboards/upstairs-mobile-dashboard.yaml  
```

As far as I know, this is how you have to define yaml dashboards, or at least there's not a way that I am aware of to define them in `ui-lovelace.yaml` (which wouldn't really make sense because `ui-lovelace.yaml` is really just the "main" dashboard).

Am I out of luck? Is there any way to make lovelace_gen work on multiple dashboards like I have?
