### ISSUE TITLE
Using state in jinja

### ISSUE THREAD

**Issue by rolfberkenbosch** [thomasloven/hass-lovelace_gen#4]
Hi,

Quick question, the following is not working. I get the error:
jinja2.exceptions.UndefinedError: 'states' is undefined

How can i make it work:

```
        {% for state in states.plant %}
        # Alarm Triggered
        - type: conditional
          conditions:
            - entity: {{ state.entity_id | lower }}
              state: "problem"
          card:
            type: horizontal-stack
            cards:
              - !include ../includes/blank-card.yaml
              - type: custom:decluttering-card
                template: notification
                variables:
                  - entity: input_boolean.notification_alarm
                  - icon: mdi:flower
                  - name: "[[[ return `Plant ${states['{{p}}'].attributes.friendly_name} heeft ${states['{{p}}'].attributes.problem}.` ]]]"
                  - card_color: 'rgba(46, 125, 50, 0.5)'
              - !include ../includes/blank-card.yaml
        {% endfor %}
```

Thanks!
