### ISSUE TITLE
invalid key: "OrderedDict([('entity', None)])"

### ISSUE THREAD

**Issue by biiiink** [thomasloven/hass-lovelace_gen#41]
I just noticed that I am getting this error on one of my dashboards:

```
Logger: custom_components.lovelace_gen
Source: custom_components/lovelace_gen/__init__.py:34
Integration: Lovelace Gen ([documentation](http://192.168.20.14:8123/config/logs))
First occurred: 10:43:53 AM (19 occurrences)
Last logged: 10:53:18 AM

invalid key: "OrderedDict([('entity', None)])" in "/config/lovelace/dashboards/mobile/includes/lights.yaml", line 3, column 0
```

the elements im using all look like this:

```
            - !include
              - includes/lights.yaml
              - entity: light.back_door
                name: Back Door Light
                top: 25%
                left: 1%
                transform: "scale(1.5)"
                type: slider
```

And this is lights.yaml
```
# lovelace_gen
type: state-icon
entity: { { entity } }
icon: mdi:lightbulb
style:
  top: { { top } }
  left: { { left } }
  transform: { { transform } }
tap_action:
  action: toggle
hold_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: { { name } }
    larger: true
    style:
      width: 100%
      height: 100%
    card:
      type: "custom:light-popup-card"
      entity: { { entity } }
      icon: mdi:lightbulb
```

One thing i did notice is that all of the variables are now wrapped in "{ {" instead of "{{".  Not sure if this will affect anything.  I did try to remove the spaces, but the Studio Code Server add-on adds the space back in when I save
