### ISSUE TITLE
Question: Include variables from file?

### ISSUE THREAD

**Issue by Aleborg** [thomasloven/hass-lovelace_gen#49]
Is it possible somehow to include variables from another file somehow?

I tried these two methods, but actually didn't expect it to work (and it didn't):

```yaml
views: !include 
  - common/views.yaml
  - config: !include json-settings.yaml
```
and in  json-settings.yaml:

```yaml
'{ "settingA": true, "settingB": false }'
```

And this version as well:

```yaml
views: !include 
  - common/views.yaml
  - !include json-settings.yaml
```
and in  json-settings.yaml:

```yaml
config: '{ "settingA": true, "settingB": false }'
```

Also tried using jinja2 include without success.
I'm trying to avoid using global variables (requires a restart of HA) 

Does anyone have any ideas on how to solve this?
