### ISSUE TITLE
[FR] Using templating 

### ISSUE THREAD

**Issue by dwainscheeren** [thomasloven/hass-lovelace_gen#5]
Hi Thomas,

Do you think its possible to tweak this module to also use home assistant templating inside yaml instead of only jinja2 ?

Like doing:
```
{% for room in states.group.rooms.attributes.entity_id %}
{% set parts = room.split('.') -%}
- title: {{ parts[1] }}
  path: rooms/{{ parts[1] }}
  cards:   
    #Some cards
{% endfor %}
```

And my `groups.yaml` :
```
rooms:
  name: Kamers
  entities:
    - group.living_room

living_room:
  name: woonkamer
  entities: 
    - light.woonkamer_spot_2
```
