### ISSUE TITLE
Configuration errors detected: unknown tag !<!include> 

### ISSUE THREAD

**Issue by sagilo** [thomasloven/hass-lovelace_gen#53]
Using latest HA version 2023.9.2
Frontend 20230911.0 - latest

UI doesnt accept the `!include` in any way, not sure what I am missing as I copied most of the configuration from the readme in the repo

<img width="972" alt="image" src="https://github.com/thomasloven/hass-lovelace_gen/assets/5019344/2826b5c8-6f89-427e-8f6b-c48b3e6b8e3d">

My card:
```yaml
type: horizontal-stack
cards:
  - !include
    - button_mobile_light_card.yaml
    - entity: light.living_room
      name: Main
```

`button_mobile_light_card.yaml` exists and has simple card layout for testing so it doesn't seem to be the issue
