### ISSUE TITLE
Feature: Access globals from Jinja Templates

### ISSUE THREAD

**Issue by PeteRager** [thomasloven/hass-lovelace_gen#57]
Feature: have the Lovelace global definitions be available in HA templates and automations.  This would allow the metadata to be used in automations (or anywhere Jinja is used).  I'm willing to do the work.

Use Case: I'm using this metadata to create an object model as part of the process of generating config.

Here is an example of a light control:

```
- name: basement_stairs
  type: switch
  targets: basement_stairs
  triggers: binary_sensor.basement_door_open,binary_sensor.basement_motion_detected 
  occupancy: binary_sensor.basement_rf_motion_detected,binary_sensor.basement_motion_detected,binary_sensor.ms_basement_door,binary_sensor.ms_basement_cam,binary_sensor.ms_furnace_cam,binary_sensor.basement_lf_motion_detected,binary_sensor.basement_lr_motion_detected 
  luminance: sensor.basement_luminance 
  delay: 
- name: basement_right
  type: switch
  targets: basement_right
  triggers: binary_sensor.basement_rf_motion_detected,binary_sensor.basement_motion_detected 
  occupancy: binary_sensor.basement_rf_motion_detected,binary_sensor.basement_motion_detected,binary_sensor.ms_basement_cam,binary_sensor.ms_furnace_cam,binary_sensor.basement_lf_motion_detected,binary_sensor.basement_lr_motion_detected 
  luminance: sensor.basement_luminance 
  delay:
```

So right now, I use that config to generate packages (templates and automations) using sed and yq to essentially replicate the package for each object to put in the right sensors, delays etc.  With the metadata available this process could be simplified.
