### ISSUE TITLE
Help with defining variables in Lovelace Gen

### ISSUE THREAD

**Issue by soloam** [thomasloven/hass-lovelace_gen#9]
Hello @thomasloven I'm sitting up a tab in my lovelace, that should work as a simple way to my kids to  play movies on the TV. I'm using the button-card custum card to make the layout, and now using Lovelace Gen to display one card for movie. This is working to some point:

```
# lovelace_gen
title: Filmes
icon: mdi:filmstrip
panel: true
path: movies_{{ library }}
cards:
 # - !include ../cards/header.yaml
  - type: vertical-stack
    cards:
    - type: custom:layout-card
      layout: horizontal
      min_columns: 2
      cards:
      {% for i in range(1, 100, 1) %}
        - type: custom:button-card
          template: recent_movie
          entity: sensor.kodi_movies
          variables:
            index: {{i}}
            library: {{ library }}
      {% endfor %}
```

The problem is that I have set "100" to display the cards, but I would like this value to be dynamic, I have a sensor with the json values that I use in button-card to get the images and descriptions of the movie, that sensor is a JSON Array with several objects.

The question is, can I replace that hard coded 100 with the array length of the JSON attribute of that sensor?

Thank You
